name: Feature Request
description: Request a new feature?
labels: [ enhancement ]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature request?
      description: |
        Please leave a helpful description of the feature request here.
    validations:
      required: true

  - type: textarea
    id: documentation
    attributes:
      label: Provide a documentation link
      description: |
        Please provide any links to the documentation. This will help us with this
        feature request.

  - type: textarea
    id: additional
    attributes:
      label: Additional Information?
