name: Shell Script Formatting

on: [push, pull_request]

jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shfmt
        run: sudo apt-get install -y shfmt
      - name: Run shfmt
        run: shfmt -d .